# Generated by Django 3.1 on 2020-08-25 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_auto_20200824_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamentomodel',
            options={'ordering': ['-name'], 'verbose_name': 'Departamento de prueba', 'verbose_name_plural': 'Áreas de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='departamentomodel',
            unique_together={('name', 'short_name')},
        ),
    ]
