# Generated by Django 3.0.3 on 2020-08-24 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prueba',
            name='cantidad',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prueba',
            name='subtitulo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
