# Generated by Django 3.1 on 2020-08-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0003_auto_20200825_1545'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabilidadesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidad')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habiidades empleados',
            },
        ),
        migrations.AlterModelOptions(
            name='empleadomodel',
            options={'ordering': ['-first_name', 'last_name'], 'verbose_name': 'Modelo Empleado de prueba', 'verbose_name_plural': 'Empleados de la empresa'},
        ),
        migrations.AlterUniqueTogether(
            name='empleadomodel',
            unique_together={('first_name', 'departamento')},
        ),
    ]
