# Generated by Django 3.1 on 2020-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20200825_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleadomodel',
            name='habilidades',
            field=models.ManyToManyField(to='persona.HabilidadesModel'),
        ),
    ]
